spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nav_links?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    name: nav_links
    username: root # ????mysql???
    password: 233233 # ????mysql??
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: hanami@233323332333233323332333233323332333
  expiration: 86400000 # token????, ???1?

